### ISSUE TITLE
App fails to resolve .local address

### ISSUE THREAD

**Issue by Aaryanjadhav11** [UtkarshJagtap/dipmachin_app#1]
_**Describe the bug**
App fails to connect to the machine because it can not resolve .local address

**To Reproduce**
Build and run this app on Android version 12 or below

**Expected behavior**
App should be able to resolve .local address and connect to the dip machine

**Additional context**
I have tried running it on a tablet and an android phone (version 10 and 12 respectively). Though It works fine on IOS stimulator but I haven't tried running it on an acutal devices.

**Comment by UtkarshJagtap** [comment]
Currently, the app relies on the operating system to resolve the `.local `address. I've observed similar behavior on my Android 12 device, where it sometimes fails to resolve this address. I'm unsure why this occurs, as Android 12 introduced support for resolving `.local` addresses. On the other hand, iOS seems to handle this process reliably.

To fix this I will try to resolve address by finding the service on the network, if found, it will use its ip and the port no. for connecting to the server

**Comment by Aaryanjadhav11** [comment]
Sounds good. thanks and good luck.

**Comment by UtkarshJagtap** [comment]
this issue has been solved in this commit 722eb9980cfc928c42bc065be9daf37320106540
